### ISSUE TITLE
Support for Python 3.13 freethreading build

### ISSUE THREAD

**Issue by greglucas** [shapely/shapely#2137]
I am starting to build Cartopy to support Python 3.13t and Shapely is one of our dependencies that we interact with through Cython and the C-layer. I couldn't find any issues discussing the current status of Shapely's support for free threading or if there are plans to work on this at all, so I figured I would open up an issue and draft PR with some simple updates to enable the free threading build to discuss this.

Is libgeos thread safe? https://libgeos.org/project/rfcs/rfc03/ I am not sure what the status of that RFC for the C-API is.

A link to some good discussion for how to approach various thread unsafe C-API usages: https://py-free-threading.github.io/porting/

**Comment by caspervdw** [comment]
There has been some news on this subject, but I am not sure if this makes shapely completely "freethreading" ready.

In #2343 we eliminated the global GEOS context that was used (only) in the geometry deallocator. Instead we started using a threadlocal GEOS context. This threadlocal GEOS context is now used BTW for every GEOS operation, not only the geometry deallocator.

Stuff that needs to happen still (based on https://py-free-threading.github.io/porting/):

- [ ] Define and document thread-safety guarantees
- [ ] Be explicit about that we don't support mutating shared ndarrays (like numpy) see discussion in #2338
- [ ] Go through all mutable global state and see if it is needed to make threadlocals (#2343 did the most part of it)
- [ ] Check if we have mutable global caches (I think not)
- [ ] Check if the Geometry classes are thread-safe (do they have mutable state?)
- [x] Declare free-threaded support in the C-extension (already done in #2138)
- [ ] Review usage of the `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS` macros
